# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 1

[[main]]
  identifier = "experience"
  name = "Experiences"
  weight = 20

  [[main]]
    parent = "experience"
    name = "ğŸ§‘ğŸ»â€ğŸ’» Industry Experience"
    url = "experience/industry"
    weight = 20

  [[main]]
    parent = "experience"
    name = "ğŸ‘¨ğŸ»â€ğŸ« Teaching Experience"
    url = "experience/teaching"
    weight = 10

[[main]]
  name = "Achievements"
  url = "achievements"
  weight = 28


[[main]]
  identifier = "skills"
  name = "Skills"
  weight = 30

  [[main]]
    parent = "skills"
    name = "ğŸ”¨ DevOps"
    url = "skills/devops"
    weight = 10

  [[main]]
    parent = "skills"
    name = "ğŸ”’ Security"
    url = "skills/security"
    weight = 20

  [[main]]
    parent = "skills"
    name = "ğŸ–¥ Backend/Frontend"
    url = "skills/development"
    weight = 30

  [[main]]
    parent = "skills"
    name = "ğŸ§  ML/Data science"
    url = "skills/ml"
    weight = 40

  [[main]]
    parent = "skills"
    name = "ğŸ“š Projects"
    url = "projects"
    weight = 100

[[main]]
  identifier = "academics"
  name = "Academics"
  weight = 50

  [[main]]
    parent = "academics"
    name = "ğŸ“– Courses"
    url = "courses/"
    weight = 1
  
  [[main]]
    parent = "academics"
    name = "ğŸ–Š Publications"
    url = "publication"
    weight = 2

[[main]]
  identifier = "blog"
  name = "Blogs"
  weight = 80

  [[main]]
      parent = "blog"
      name = "ğŸ’» DevRa - Tech Blog"
      url = "https://rafed.github.io/devra/"
      weight = 1

  [[main]]
      parent = "blog"
      name = "ğŸ‘¤ Personal Blog"
      url = "https://rafed.github.io/blog/"
      weight = 2

[[main]]
  identifier = "other"
  name = "Others"
  weight = 90

  [[main]]
      parent = "other"
      name = "ğŸ“° Recent News"
      url = "#recent-news"
      weight = 10

  [[main]]
      parent = "other"
      name = "ğŸ“† Events"
      url = "event/"
      weight = 20

  [[main]]
      parent = "other"
      name = "ğŸ¸ Hobbies"
      url = "hobbies/"
      weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100

[[main]]
  name = "â˜•"
  url = "https://www.buymeacoffee.com/rafed"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
